server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  datasource:
    url: jdbc:mariadb://localhost:3306/cake
    username: root
    password: 28782821
    driver-class-name: org.mariadb.jdbc.Driver

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB
  data:
    redis:
      host: localhost
      port: 6379
